import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import { useContext } from "react";
import AppContext from "../context";
import ReactHtmlParser from "react-html-parser";
export default function Home({
  setProfileInfo,
  connectWallet,
  createProfile,
  onChangeCoverImg,
  onChangeProfileImg,
}) {
  const {
    account,
    profileInfo,
    isCreator,
    fetchedProfile,
    profileLoading,
    fetchedPosts,
  } = useContext(AppContext);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="App">
        {account ? (
          <Link href={`profile/${account}`}>Profile</Link>
        ) : (
          <button onClick={connectWallet}>Connect Wallet</button>
        )}
      </div>
    </div>
  );
}
